[project]
name = "encore"
target = "auto"
version = "0.0.0"
description = ""
readme = "README.md"
licence = "MIT"
dependencies = [
    "path@../index/std",
    # "path@../index/toml",
    # "path@../index/ehir",
    # "path@refrains/ehir-llvm-backend"
]
