[project]
name = "bare_metal"
version = "0.0.0"
target = "thumbv7em-none-eabi"
dependencies = []

[target.thumbv7em-none-eabi]
builtin-runtime = false
cpu = "cortex-m4"
runtime-sources = ["platform/startup.c"]
linker-script = "platform/memory.ld"
compile-args = [
    "-ffunction-sections",
    "-fdata-sections",
    "-fno-unwind-tables",
    "-fno-asynchronous-unwind-tables",
]
link-args = ["-nostdlib", "-fuse-ld=lld", "-Wl,--gc-sections", "-Wl,--build-id=none"]
