[project]
name = "encore"
version = "0.1.4"
description = ""
readme = "README.md"
licence = "MIT"
dependencies = [ "index@std@1.0.0", "index@rich@1.0.0", "index@json@1.0.0", "index@ehirlib@0.0.0", "index@ehir_llvm_backend@0.0.0", "index@toml@1.0.0", "index@colorterm@1.0.0",]

[target.x86_64-unknown-linux-gnu]
link-args = ["-lssl", "-lcrypto"]

[target.aarch64-unknown-linux-gnu]
link-args = ["-lssl", "-lcrypto"]
