[project]
name = "encore"
version = "0.1.3"
description = ""
readme = "README.md"
licence = "MIT"
dependencies = [ "path@index/std", "path@index/rich", "path@index/json", "path@index/ehir", "path@index/ehir-llvm-backend", "path@index/toml", "path@index/colorterm",]
