[project]
name = "encore"
version = "0.1.0"
description = "Encore Programming Language Compiler"
readme = "README.md"
authors = [
    { name = "Maksim Shushkevich", email = "m.e.shushkevich@yandex.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "ehir-llvm-backend",
    "ehir",
    "pydantic>=2.12.5",
    "toml>=0.10.2",
    "gitpython>=3.1.46",
    "rich>=14.3.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "ruff>=0.14.11",
    "ty>=0.0.10",
]

[tool.uv.sources]
ehir = { git = "https://github.com/encore-language/ehir", branch = "trunk" }
ehir-llvm-backend = { path = "backends/ehir-llvm-backend", editable = true }

[project.scripts]
encore = "encore.cli:main"

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"
