[project]
name = "decorator_profile"
version = "0.0.0"
description = "Compile-time function decorator and profiling example"
readme = "README.md"
licence = "MIT"
dependencies = ["path@../../../encore-index/packages/profile"]
