[project]
name = "graphene"
target = "auto"
version = "0.0.0"
description = "Native GUI and game-engine foundation for Encore"
readme = "README.md"
licence = "MIT"
dependencies = [ "path@./gui_core", "path@./gui_native",]
