[project]
name = "graphene"
version = "0.1.0"
description = "Graphene real-time engine and editor"
readme = "README.md"
licence = "MIT"
build = "build.enq"
dependencies = [
    "path@../json",
    "path@../linalg",
    "workspace@vulkan_native",
]
