[project]
name = "hello_server"
version = "0.0.0"
description = "Minimal TCP server returning Hello, World!"
readme = "README.md"
licence = "MIT"
dependencies = ["path@../../../encore-index/packages/std"]
