[project]
name = "encore"
version = "0.0.0"
description = ""
readme = "README.md"
licence = "MIT"
dependencies = [ "path@../std", "path@../rich", "path@../ehir", "path@../ehir-llvm-backend", "path@../toml", "path@../colorterm",]
