[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ehir"
description = "Encore High Intermediate Representation"
readme = "README.md"
authors = [
    {name = "Maksim Shushkevich", email = "m.e.shushkevich@yandex.com"}
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "llvmlite>=0.46.0",
    "rich>=14.2.0",
]
dynamic = ["version"]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "ruff>=0.14.10",
    "ty>=0.0.8",
]

[project.scripts]
ehir = "ehir.cli:main"

[tool.setuptools.dynamic]
version = {file = "VERSION"}
