[project]
name = "gui_native"
target = "auto"
version = "0.0.0"
description = "Native GUI backend"
readme = "README.md"
licence = "MIT"
dependencies = [ "path@../gui_core",]

[native]
libraries = [
    { name = "X11", cfg = "linux" },
    { name = "user32", cfg = "windows" },
    { name = "gdi32", cfg = "windows" },
    { name = "Cocoa", kind = "framework", cfg = "macos" },
]
