[project]
name = "refrains"
version = "0.0.0"
description = "Add description here"
readme = "README.md"
licence = "MIT"
dependencies = [
    "git@https://github.com/encore-language/stdlib",
    "path@math"
]
