[project]
name = "encore-lsp"
version = "0.1.0"
description = "Encore language server implemented in Encore"
readme = "README.md"
licence = "MIT"
dependencies = [
    "path@../bootstrap",
    "path@../index/json"
]
